
// 练习
// var dsq = window.setInterval(function () {
//     function get_random (min, max) {
//         return	Math.floor(Math.random()*(max-min+1)+min);
//     }
    
//     var juli = get_random (10, 500);
//     var topp = get_random (30, 800);
//     var julii = get_random (10, 500);
//     var toppi = get_random (50, 600);
//     $('.her').css('left',julii).css('top',toppi)
//     $('.hero').css('left',juli).css('top',topp)

// },500)

// var i = 0
// $('.hero').click(function(){ 
//     i++;
//     if (i%2 == 0) {
//         window.clearInterval(dsq);
//     }else {
//         window.setInterval()
//     }
    
// })


var cike = [
    { name: '暗夜猎手', imgSrc: '暗夜猎手.png' },
    { name: '傲之追猎者', imgSrc: '傲之追猎者.png' },
    { name: '不祥之刃', imgSrc: '不祥之刃.png' },
    { name: '潮汐海灵', imgSrc: '潮汐海灵.png' },
    { name: '刀锋舞者', imgSrc: '刀锋舞者.png' },
    { name: '刀锋之影', imgSrc: '刀锋之影.png' },
    { name: '德邦总管', imgSrc: '德邦总管.png' },
    { name: '恶魔小丑', imgSrc: '恶魔小丑.png' },
    { name: '放逐之刃', imgSrc: '放逐之刃.png' },
    { name: '诡术妖姬', imgSrc: '诡术妖姬.png' },
    { name: '疾风剑豪', imgSrc: '疾风剑豪.png' },
    { name: '九尾狐妖', imgSrc: '九尾狐妖.png' },
    { name: '狂野女猎手', imgSrc: '狂野女猎手.png'},
    { name: '离群之刺', imgSrc: '离群之刺.png' },
    { name: '麦林炮手', imgSrc: '麦林炮手.png' },
    { name: '蛮族之王', imgSrc: '蛮族之王.png' },
    { name: '盲僧', imgSrc: '盲僧.png' },
    { name: '皮城执法官', imgSrc: '皮城执法官.png' },
    { name: '时间刺客', imgSrc: '时间刺客.png' },
    { name: '痛苦之拥', imgSrc: '痛苦之拥.png' },
    { name: '瘟疫之源', imgSrc: '瘟疫之源.png' },
    { name: '无极剑圣', imgSrc: '无极剑圣.png' },
    { name: '无双剑姬', imgSrc: '无双剑姬.png' },
    { name: '武器大师', imgSrc: '武器大师.png' },
    { name: '戏命师', imgSrc: '戏命师.png' },
    { name: '虚空行者', imgSrc: '虚空行者.png' },
    { name: '虚空掠夺者', imgSrc: '虚空掠夺者.png' },
    { name: '虚空先知', imgSrc: '虚空先知.png' },
    { name: '血港鬼影', imgSrc: '血港鬼影.png' },
    { name: '迅捷斥候', imgSrc: '迅捷斥候.png' },
    { name: '影流之镰', imgSrc: '影流之镰.png' },
    { name: '影流之王', imgSrc: '影流之王.png' },
    { name: '永恒梦魇', imgSrc: '永恒梦魇.png' },
    { name: '远古巫灵', imgSrc: '远古巫灵.png' },
    { name: '战争之王', imgSrc: '战争之王.png' }
  ];

var fashi = [
    { name: '暗黑元首', imgSrc: '暗黑元首.png' },
    { name: '爆破鬼才', imgSrc: '爆破鬼才.png' },
    { name: '冰晶凤凰', imgSrc: '冰晶凤凰.png' },
    { name: '冰霜女皇', imgSrc: '冰霜女皇.png' },
    { name: '不祥之刃', imgSrc: '不祥之刃.png' },
    { name: '惩戒之箭', imgSrc: '惩戒之箭.png' },
    { name: '翠神', imgSrc: '翠神.png' },
    { name: '大发明家', imgSrc: '大发明家.png' },
    { name: '堕落天使', imgSrc: '堕落天使.png' },
    { name: '发条魔灵', imgSrc: '发条魔灵.png' },
    { name: '风暴之怒', imgSrc: '风暴之怒.png' },
    { name: '符文法师', imgSrc: '符文法师.png' },
    { name: '复仇焰魂', imgSrc: '复仇焰魂.png' },
    { name: '光辉女郎', imgSrc: '光辉女郎.png' },
    { name: '诡术妖姬', imgSrc: '诡术妖姬.png' },
    { name: '黑暗之女', imgSrc: '黑暗之女.png' },
    { name: '唤潮鲛姬', imgSrc: '唤潮鲛姬.png' },
    { name: '机械公敌', imgSrc: '机械公敌.png' },
    { name: '机械先驱', imgSrc: '机械先驱.png' },
    { name: '皎月女神', imgSrc: '皎月女神.png' },
    { name: '荆棘之兴', imgSrc: '荆棘之兴.png' },
    { name: '九尾狐妖', imgSrc: '九尾狐妖.png' },
    { name: '酒桶', imgSrc: '酒桶.png' },
    { name: '卡牌大师', imgSrc: '卡牌大师.png' },
    { name: '狂暴之心', imgSrc: '狂暴之心.png' },
    { name: '魔蛇之拥', imgSrc: '魔蛇之拥.png' },
    { name: '末日使者', imgSrc: '末日使者.png' },
    { name: '暮光星灵', imgSrc: '暮光星灵.png' },
    { name: '扭曲树精', imgSrc: '扭曲树精.png' },
    { name: '诺克萨斯统领', imgSrc: '诺克萨斯统领.png' },
    { name: '琴瑟仙女', imgSrc: '琴瑟仙女.png' },
    { name: '沙漠皇帝', imgSrc: '沙漠皇帝.png' },
    { name: '殇之木乃伊', imgSrc: '殇之木乃伊.png' },
    { name: '深渊巨口', imgSrc: '深渊巨口.png' },
    { name: '时光守护者', imgSrc: '时光守护者.png' },
    { name: '死亡歌颂者', imgSrc: '死亡歌颂者.png' },
    { name: '探险家', imgSrc: '探险家.png' },
    { name: '天启者', imgSrc: '天启者.png' },
    { name: '痛苦之拥', imgSrc: '痛苦之拥.png' },
    { name: '万花通灵', imgSrc: '万花通灵.png' },
    { name: '仙灵女巫', imgSrc: '仙灵女巫.png' },
    { name: '邪恶小法师', imgSrc: '邪恶小法师.png' },
    { name: '星界游神', imgSrc: '星界游神.png' },
    { name: '猩红收割者', imgSrc: '猩红收割者.png' },
    { name: '虚空行者', imgSrc: '虚空行者.png' },
    { name: '虚空恐惧', imgSrc: '虚空恐惧.png' },
    { name: '虚空先知', imgSrc: '虚空先知.png' },
    { name: '虚空之眼', imgSrc: '虚空之眼.png' },
    { name: '岩雀', imgSrc: '岩雀.png' },
    { name: '远古巫灵', imgSrc: '远古巫灵.png' },
    { name: '正义巨像', imgSrc: '正义巨像.png' },
    { name: '蜘蛛女皇', imgSrc: '蜘蛛女皇.png' },
    { name: '众星之子', imgSrc: '众星之子.png' },
    { name: '铸星龙王', imgSrc: '铸星龙王.png' }
  ];

var fuzhu = [
    { name: '暗黑元首', imgSrc: '暗黑元首.png' },
    { name: '冰晶凤凰', imgSrc: '冰晶凤凰.png' },
    { name: '翠神', imgSrc: '翠神.png' },
    { name: '大发明家', imgSrc: '大发明家.png' },
    { name: '堕落天使', imgSrc: '堕落天使.png' },
    { name: '发条魔灵', imgSrc: '发条魔灵.png' },
    { name: '风暴之怒', imgSrc: '风暴之怒.png' },
    { name: '弗雷尔卓德之心', imgSrc: '弗雷尔卓德之心.png' },
    { name: '光辉女郎', imgSrc: '光辉女郎.png' },
    { name: '寒冰射手', imgSrc: '寒冰射手.png' },
    { name: '河流之王', imgSrc: '河流之王.png' },
    { name: '幻翎', imgSrc: '幻翎.png' },
    { name: '唤潮鲛姬', imgSrc: '唤潮鲛姬.png' },
    { name: '魂锁典狱长', imgSrc: '魂锁典狱长.png' },
    { name: '荆棘之兴', imgSrc: '荆棘之兴.png' },
    { name: '末日使者', imgSrc: '末日使者.png' },
    { name: '暮光星灵', imgSrc: '暮光星灵.png' },
    { name: '牛头酋长', imgSrc: '牛头酋长.png' },
    { name: '琴瑟仙女', imgSrc: '琴瑟仙女.png' },
    { name: '审判天使', imgSrc: '审判天使.png' },
    { name: '时光守护者', imgSrc: '时光守护者.png' },
    { name: '曙光女神', imgSrc: '曙光女神.png' },
    { name: '天启者', imgSrc: '天启者.png' },
    { name: '瓦罗兰之盾', imgSrc: '瓦罗兰之盾.png' },
    { name: '万花通灵', imgSrc: '万花通灵.png' },
    { name: '仙灵女巫', imgSrc: '仙灵女巫.png' },
    { name: '星界游神', imgSrc: '星界游神.png' },
    { name: '血港鬼影', imgSrc: '血港鬼影.png' },
    { name: '岩雀', imgSrc: '岩雀.png' },
    { name: '众星之子', imgSrc: '众星之子.png' }
  ];


var sheshou = [
    { name: '暗夜猎手', imgSrc: '暗夜猎手.png' },
    { name: '暴走萝莉', imgSrc: '暴走萝莉.png' },
    { name: '惩戒之箭', imgSrc: '惩戒之箭.png' },
    { name: '德玛西亚之翼', imgSrc: '德玛西亚之翼.png' },
    { name: '法外狂徒', imgSrc: '法外狂徒.png' },
    { name: '复仇之矛', imgSrc: '复仇之矛.png' },
    { name: '寒冰射手', imgSrc: '寒冰射手.png' },
    { name: '狂暴之心', imgSrc: '狂暴之心.png' },
    { name: '麦林炮手', imgSrc: '麦林炮手.png' },
    { name: '逆羽', imgSrc: '逆羽.png' },
    { name: '皮城女警', imgSrc: '皮城女警.png' },
    { name: '荣耀行刑官', imgSrc: '荣耀行刑官.png' },
    { name: '沙漠皇帝', imgSrc: '沙漠皇帝.png' },
    { name: '赏金猎人', imgSrc: '赏金猎人.png' },
    { name: '深渊巨口', imgSrc: '深渊巨口.png' },
    { name: '圣枪游侠', imgSrc: '圣枪游侠.png' },
    { name: '探险家', imgSrc: '探险家.png' },
    { name: '未来守护者', imgSrc: '未来守护者.png' },
    { name: '瘟疫之源', imgSrc: '瘟疫之源.png' },
    { name: '无畏战车', imgSrc: '无畏战车.png' },
    { name: '戏命师', imgSrc: '戏命师.png' },
    { name: '虚空之女', imgSrc: '虚空之女.png' },
    { name: '迅捷斥候', imgSrc: '迅捷斥候.png' },
    { name: '英勇投弹手', imgSrc: '英勇投弹手.png' },
    { name: '永猎双子', imgSrc: '永猎双子.png' },
    { name: '战争女神', imgSrc: '战争女神.png' }
  ];

var zhanshi = [
    { name: '暗裔剑魔 ', imgSrc: '暗裔剑魔 .png' },
    { name: '傲之追猎者', imgSrc: '傲之追猎者.png' },
    { name: '暴怒骑士', imgSrc: '暴怒骑士.png' },
    { name: '北地之怒', imgSrc: '北地之怒.png' },
    { name: '潮汐海灵', imgSrc: '潮汐海灵.png' },
    { name: '刀锋舞者', imgSrc: '刀锋舞者.png' },
    { name: '刀锋之影', imgSrc: '刀锋之影.png' },
    { name: '德邦总管', imgSrc: '德邦总管.png' },
    { name: '德玛西亚皇子', imgSrc: '德玛西亚皇子.png' },
    { name: '德玛西亚之力', imgSrc: '德玛西亚之力.png' },
    { name: '德玛西亚之翼', imgSrc: '德玛西亚之翼.png' },
    { name: '放逐之刃', imgSrc: '放逐之刃.png' },
    { name: '符文法师', imgSrc: '符文法师.png' },
    { name: '海兽祭司', imgSrc: '海兽祭司.png' },
    { name: '海洋之灾', imgSrc: '海洋之灾.png' },
    { name: '荒漠屠夫', imgSrc: '荒漠屠夫.png' },
    { name: '魂锁典狱长', imgSrc: '魂锁典狱长.png' },
    { name: '机械公敌', imgSrc: '机械公敌.png' },
    { name: '疾风剑豪', imgSrc: '疾风剑豪.png' },
    { name: '皎月女神', imgSrc: '皎月女神.png' },
    { name: '酒桶', imgSrc: '酒桶.png' },
    { name: '巨魔之王', imgSrc: '巨魔之王.png' },
    { name: '狂野女猎手', imgSrc: '狂野女猎手.png' },
    { name: '狂战士', imgSrc: '狂战士.png' },
    { name: '雷霆咆哮', imgSrc: '雷霆咆哮.png' },
    { name: '炼金术士', imgSrc: '炼金术士.png' },
    { name: '龙血武姬', imgSrc: '龙血武姬.png' },
    { name: '蛮族之王', imgSrc: '蛮族之王.png' },
    { name: '盲僧', imgSrc: '盲僧.png' },
    { name: '迷失之牙', imgSrc: '迷失之牙.png' },
    { name: '牧魂人', imgSrc: '牧魂人.png' },
    { name: '诺克萨斯统领', imgSrc: '诺克萨斯统领.png' },
    { name: '诺克萨斯之手', imgSrc: '诺克萨斯之手.png' },
    { name: '披甲龙龟', imgSrc: '披甲龙龟.png' },
    { name: '皮城执法官', imgSrc: '皮城执法官.png' },
    { name: '齐天大圣', imgSrc: '齐天大圣.png' },
    { name: '青钢影', imgSrc: '熔岩巨兽.png' },
    { name: '沙漠死神', imgSrc: '沙漠死神.png' },
    { name: '山隐之焰', imgSrc: '山隐之焰.png' },
    { name: '深海泰坦', imgSrc: '深海泰坦.png' },
    { name: '审判天使', imgSrc: '审判天使.png' },
    { name: '生化魔人', imgSrc: '生化魔人.png' },
    { name: '圣锤之殿', imgSrc: '圣锤之殿.png' },
    { name: '时间刺客', imgSrc: '时间刺客.png' },
    { name: '兽灵行者', imgSrc: '兽灵行者.png' },
    { name: '水晶先锋', imgSrc: '水晶先锋.png' },
    { name: '铁甲冥魂', imgSrc: '铁甲冥魂.png' },
    { name: '瓦罗兰之盾', imgSrc: '瓦罗兰之盾.png' },
    { name: '亡灵战神', imgSrc: '亡灵战神.png' },
    { name: '未来守护者', imgSrc: '未来守护者.png' },
    { name: '无极剑圣', imgSrc: '无极剑圣.png' },
    { name: '无双剑姬', imgSrc: '无双剑姬.png' },
    { name: '无畏战车', imgSrc: '无畏战车.png' },
    { name: '武器大师', imgSrc: '武器大师.png' },
    { name: '虚空遁地兽', imgSrc: '虚空遁地兽.png' },
    { name: '虚空掠夺者', imgSrc: '虚空掠夺者.png' },
    { name: '雪原双子', imgSrc: '雪原双子.png' },
    { name: '影流之镰', imgSrc: '影流之镰.png' },
    { name: '影流之王', imgSrc: '影流之王.png' },
    { name: '永恒梦魇', imgSrc: '永恒梦魇.png' },
    { name: '战争之王', imgSrc: '战争之王.png' },
    { name: '战争之影', imgSrc: '战争之影.png' },
    { name: '蒸汽机器人', imgSrc: '蒸汽机器人.png' },
    { name: '蜘蛛女皇', imgSrc: '蜘蛛女皇.png' },
    { name: '铸星龙王', imgSrc: '铸星龙王.png' },
    { name: '祖安狂人', imgSrc: '祖安狂人.png' },
    { name: '祖安怒兽', imgSrc: '祖安怒兽.png' }
  ];

var tanke = [
    { name: '暗裔剑魔 ', imgSrc: '暗裔剑魔 .png' },
    { name: '暴怒骑士', imgSrc: '暴怒骑士.png' },
    { name: '北地之怒', imgSrc: '北地之怒.png' },
    { name: '德玛西亚皇子', imgSrc: '德玛西亚皇子.png' },
    { name: '德玛西亚之力', imgSrc: '德玛西亚之力.png' },
    { name: '弗雷尔卓德之心', imgSrc: '弗雷尔卓德之心.png' },
    { name: '海兽祭司', imgSrc: '海兽祭司.png' },
    { name: '河流之王', imgSrc: '河流之王.png' },
    { name: '荒漠屠夫', imgSrc: '荒漠屠夫.png' },
    { name: '巨魔之王', imgSrc: '巨魔之王.png' },
    { name: '狂战士', imgSrc: '狂战士.png' },
    { name: '雷霆咆哮', imgSrc: '雷霆咆哮.png' },
    { name: '炼金术士', imgSrc: '炼金术士.png' },
    { name: '龙血武姬', imgSrc: '龙血武姬.png' },
    { name: '迷失之牙', imgSrc: '迷失之牙.png' },
    { name: '牧魂人', imgSrc: '牧魂人.png' },
    { name: '暮光之眼', imgSrc: '暮光之眼.png' },
    { name: '牛头酋长', imgSrc: '牛头酋长.png' },
    { name: '扭曲树精', imgSrc: '扭曲树精.png' },
    { name: '诺克萨斯之手', imgSrc: '诺克萨斯之手.png' },
    { name: '披甲龙龟', imgSrc: '披甲龙龟.png' },
    { name: '齐天大圣', imgSrc: '齐天大圣.png' },
    { name: '青钢影', imgSrc: '青钢影.png' },
    { name: '熔岩巨兽', imgSrc: '熔岩巨兽.png' },
    { name: '沙漠死神', imgSrc: '沙漠死神.png' },
    { name: '山隐之焰', imgSrc: '山隐之焰.png' },
    { name: '殇之木乃伊', imgSrc: '殇之木乃伊.png' },
    { name: '深海泰坦', imgSrc: '深海泰坦.png' },
    { name: '生化魔人', imgSrc: '生化魔人.png' },
    { name: '圣锤之殿', imgSrc: '圣锤之殿.png' },
    { name: '兽灵行者', imgSrc: '兽灵行者.png' },
    { name: '曙光女神', imgSrc: '曙光女神.png' },
    { name: '水晶先锋', imgSrc: '水晶先锋.png' },
    { name: '亡灵战神', imgSrc: '亡灵战神.png' },
    { name: '猩红收割者', imgSrc: '猩红收割者.png' },
    { name: '虚空恐惧', imgSrc: '虚空恐惧.png' },
    { name: '雪原双子', imgSrc: '雪原双子.png' },
    { name: '战争之影', imgSrc: '战争之影.png' },
    { name: '蒸汽机器人', imgSrc: '蒸汽机器人.png' },
    { name: '正义巨像', imgSrc: '正义巨像.png' },
    { name: '祖安狂人', imgSrc: '祖安狂人.png' },
    { name: '祖安怒兽', imgSrc: '祖安怒兽.png' }
  ];


var allheros = [
    { name: '暗裔剑魔 ', imgSrc: '暗裔剑魔 .png' },
    { name: '傲之追猎者', imgSrc: '傲之追猎者.png' },
    { name: '暴怒骑士', imgSrc: '暴怒骑士.png' },
    { name: '北地之怒', imgSrc: '北地之怒.png' },
    { name: '潮汐海灵', imgSrc: '潮汐海灵.png' },
    { name: '刀锋舞者', imgSrc: '刀锋舞者.png' },
    { name: '刀锋之影', imgSrc: '刀锋之影.png' },
    { name: '德邦总管', imgSrc: '德邦总管.png' },
    { name: '德玛西亚皇子', imgSrc: '德玛西亚皇子.png' },
    { name: '德玛西亚之力', imgSrc: '德玛西亚之力.png' },
    { name: '德玛西亚之翼', imgSrc: '德玛西亚之翼.png' },
    { name: '放逐之刃', imgSrc: '放逐之刃.png' },
    { name: '海兽祭司', imgSrc: '海兽祭司.png' },
    { name: '海洋之灾', imgSrc: '海洋之灾.png' },
    { name: '荒漠屠夫', imgSrc: '荒漠屠夫.png' },
    { name: '魂锁典狱长', imgSrc: '魂锁典狱长.png' },
    { name: '疾风剑豪', imgSrc: '疾风剑豪.png' },
    { name: '巨魔之王', imgSrc: '巨魔之王.png' },
    { name: '狂野女猎手', imgSrc: '狂野女猎手.png' },
    { name: '狂战士', imgSrc: '狂战士.png' },
    { name: '雷霆咆哮', imgSrc: '雷霆咆哮.png' },
    { name: '炼金术士', imgSrc: '炼金术士.png' },
    { name: '龙血武姬', imgSrc: '龙血武姬.png' },
    { name: '蛮族之王', imgSrc: '蛮族之王.png' },
    { name: '盲僧', imgSrc: '盲僧.png' },
    { name: '迷失之牙', imgSrc: '迷失之牙.png' },
    { name: '牧魂人', imgSrc: '牧魂人.png' },
    { name: '诺克萨斯之手', imgSrc: '诺克萨斯之手.png' },
    { name: '披甲龙龟', imgSrc: '披甲龙龟.png' },
    { name: '皮城执法官', imgSrc: '皮城执法官.png' },
    { name: '齐天大圣', imgSrc: '齐天大圣.png' },
    { name: '青钢影', imgSrc: '熔岩巨兽.png' },
    { name: '沙漠死神', imgSrc: '沙漠死神.png' },
    { name: '山隐之焰', imgSrc: '山隐之焰.png' },
    { name: '深海泰坦', imgSrc: '深海泰坦.png' },
    { name: '审判天使', imgSrc: '审判天使.png' },
    { name: '生化魔人', imgSrc: '生化魔人.png' },
    { name: '圣锤之殿', imgSrc: '圣锤之殿.png' },
    { name: '时间刺客', imgSrc: '时间刺客.png' },
    { name: '兽灵行者', imgSrc: '兽灵行者.png' },
    { name: '水晶先锋', imgSrc: '水晶先锋.png' },
    { name: '铁甲冥魂', imgSrc: '铁甲冥魂.png' },
    { name: '瓦罗兰之盾', imgSrc: '瓦罗兰之盾.png' },
    { name: '亡灵战神', imgSrc: '亡灵战神.png' },
    { name: '未来守护者', imgSrc: '未来守护者.png' },
    { name: '无极剑圣', imgSrc: '无极剑圣.png' },
    { name: '无双剑姬', imgSrc: '无双剑姬.png' },
    { name: '无畏战车', imgSrc: '无畏战车.png' },
    { name: '武器大师', imgSrc: '武器大师.png' },
    { name: '虚空遁地兽', imgSrc: '虚空遁地兽.png' },
    { name: '虚空掠夺者', imgSrc: '虚空掠夺者.png' },
    { name: '雪原双子', imgSrc: '雪原双子.png' },
    { name: '影流之镰', imgSrc: '影流之镰.png' },
    { name: '影流之王', imgSrc: '影流之王.png' },
    { name: '永恒梦魇', imgSrc: '永恒梦魇.png' },
    { name: '战争之王', imgSrc: '战争之王.png' },
    { name: '战争之影', imgSrc: '战争之影.png' },
    { name: '蒸汽机器人', imgSrc: '蒸汽机器人.png' },
    { name: '祖安狂人', imgSrc: '祖安狂人.png' },
    { name: '祖安怒兽', imgSrc: '祖安怒兽.png' },
    { name: '暗黑元首', imgSrc: '暗黑元首.png' },
    { name: '爆破鬼才', imgSrc: '爆破鬼才.png' },
    { name: '冰晶凤凰', imgSrc: '冰晶凤凰.png' },
    { name: '冰霜女皇', imgSrc: '冰霜女皇.png' },
    { name: '不祥之刃', imgSrc: '不祥之刃.png' },
    { name: '惩戒之箭', imgSrc: '惩戒之箭.png' },
    { name: '翠神', imgSrc: '翠神.png' },
    { name: '大发明家', imgSrc: '大发明家.png' },
    { name: '堕落天使', imgSrc: '堕落天使.png' },
    { name: '发条魔灵', imgSrc: '发条魔灵.png' },
    { name: '风暴之怒', imgSrc: '风暴之怒.png' },
    { name: '符文法师', imgSrc: '符文法师.png' },
    { name: '复仇焰魂', imgSrc: '复仇焰魂.png' },
    { name: '光辉女郎', imgSrc: '光辉女郎.png' },
    { name: '诡术妖姬', imgSrc: '诡术妖姬.png' },
    { name: '黑暗之女', imgSrc: '黑暗之女.png' },
    { name: '唤潮鲛姬', imgSrc: '唤潮鲛姬.png' },
    { name: '机械公敌', imgSrc: '机械公敌.png' },
    { name: '机械先驱', imgSrc: '机械先驱.png' },
    { name: '皎月女神', imgSrc: '皎月女神.png' },
    { name: '荆棘之兴', imgSrc: '荆棘之兴.png' },
    { name: '九尾狐妖', imgSrc: '九尾狐妖.png' },
    { name: '酒桶', imgSrc: '酒桶.png' },
    { name: '卡牌大师', imgSrc: '卡牌大师.png' },
    { name: '狂暴之心', imgSrc: '狂暴之心.png' },
    { name: '魔蛇之拥', imgSrc: '魔蛇之拥.png' },
    { name: '末日使者', imgSrc: '末日使者.png' },
    { name: '暮光星灵', imgSrc: '暮光星灵.png' },
    { name: '扭曲树精', imgSrc: '扭曲树精.png' },
    { name: '诺克萨斯统领', imgSrc: '诺克萨斯统领.png' },
    { name: '琴瑟仙女', imgSrc: '琴瑟仙女.png' },
    { name: '沙漠皇帝', imgSrc: '沙漠皇帝.png' },
    { name: '殇之木乃伊', imgSrc: '殇之木乃伊.png' },
    { name: '深渊巨口', imgSrc: '深渊巨口.png' },
    { name: '时光守护者', imgSrc: '时光守护者.png' },
    { name: '死亡歌颂者', imgSrc: '死亡歌颂者.png' },
    { name: '探险家', imgSrc: '探险家.png' },
    { name: '天启者', imgSrc: '天启者.png' },
    { name: '痛苦之拥', imgSrc: '痛苦之拥.png' },
    { name: '万花通灵', imgSrc: '万花通灵.png' },
    { name: '仙灵女巫', imgSrc: '仙灵女巫.png' },
    { name: '邪恶小法师', imgSrc: '邪恶小法师.png' },
    { name: '星界游神', imgSrc: '星界游神.png' },
    { name: '猩红收割者', imgSrc: '猩红收割者.png' },
    { name: '虚空行者', imgSrc: '虚空行者.png' },
    { name: '虚空恐惧', imgSrc: '虚空恐惧.png' },
    { name: '虚空先知', imgSrc: '虚空先知.png' },
    { name: '虚空之眼', imgSrc: '虚空之眼.png' },
    { name: '岩雀', imgSrc: '岩雀.png' },
    { name: '远古巫灵', imgSrc: '远古巫灵.png' },
    { name: '正义巨像', imgSrc: '正义巨像.png' },
    { name: '蜘蛛女皇', imgSrc: '蜘蛛女皇.png' },
    { name: '众星之子', imgSrc: '众星之子.png' },
    { name: '铸星龙王', imgSrc: '铸星龙王.png' },
    { name: '弗雷尔卓德之心', imgSrc: '弗雷尔卓德之心.png' },
    { name: '海兽祭司', imgSrc: '海兽祭司.png' },
    { name: '河流之王', imgSrc: '河流之王.png' },
    { name: '暮光之眼', imgSrc: '暮光之眼.png' },
    { name: '牛头酋长', imgSrc: '牛头酋长.png' },
    { name: '曙光女神', imgSrc: '曙光女神.png' },
    { name: '祖安狂人', imgSrc: '祖安狂人.png' }, 
    { name: '暗夜猎手', imgSrc: '暗夜猎手.png' },
    { name: '暴走萝莉', imgSrc: '暴走萝莉.png' }, 
    { name: '法外狂徒', imgSrc: '法外狂徒.png' },
    { name: '复仇之矛', imgSrc: '复仇之矛.png' },
    { name: '寒冰射手', imgSrc: '寒冰射手.png' },
    { name: '麦林炮手', imgSrc: '麦林炮手.png' },
    { name: '逆羽', imgSrc: '逆羽.png' },
    { name: '皮城女警', imgSrc: '皮城女警.png' },
    { name: '荣耀行刑官', imgSrc: '荣耀行刑官.png' },
    { name: '赏金猎人', imgSrc: '赏金猎人.png' },
    { name: '圣枪游侠', imgSrc: '圣枪游侠.png' },
    { name: '瘟疫之源', imgSrc: '瘟疫之源.png' },
    { name: '戏命师', imgSrc: '戏命师.png' },
    { name: '虚空之女', imgSrc: '虚空之女.png' },
    { name: '迅捷斥候', imgSrc: '迅捷斥候.png' },
    { name: '英勇投弹手', imgSrc: '英勇投弹手.png' },
    { name: '永猎双子', imgSrc: '永猎双子.png' },
    { name: '战争女神', imgSrc: '战争女神.png' },
    { name: '幻翎', imgSrc: '幻翎.png' },
    { name: '血港鬼影', imgSrc: '血港鬼影.png' }, 
    { name: '恶魔小丑', imgSrc: '恶魔小丑.png' },
    { name: '离群之刺', imgSrc: '离群之刺.png' }
  ];

var hero_fenlei = [cike,fashi,fuzhu,sheshou,zhanshi,tanke,allheros];


var mofang = [
  { imgSrc: '1.jpg' },
  { imgSrc: '2.jpg' },
  { imgSrc: '3.jpg' },
  { imgSrc: '4.jpg' },
  { imgSrc: '5.jpg' },
  { imgSrc: '6.jpg' },
  { imgSrc: '7.jpg' },
  { imgSrc: '8.jpg' },
  { imgSrc: '9.jpg' },
  { imgSrc: '10.jpg' },
  { imgSrc: '11.jpg' },
  { imgSrc: '12.jpg' },
  { imgSrc: '13.jpg' },
  { imgSrc: '14.jpg' },
  { imgSrc: '15.jpg' },
  { imgSrc: '16.jpg' },
  { imgSrc: '17.jpg' },
  { imgSrc: '18.jpg' },
  { imgSrc: '19.jpg' },
  { imgSrc: '20.jpg' },
  { imgSrc: '21.jpg' },
  { imgSrc: '22.jpg' },
  { imgSrc: '23.jpg' },
  { imgSrc: '24.jpg' },
  { imgSrc: '25.jpg' },
  { imgSrc: '26.jpg' },
  { imgSrc: '27.jpg' },
  { imgSrc: '28.jpg' },
  { imgSrc: '29.jpg' },
  { imgSrc: '30.jpg' },
  { imgSrc: '31.jpg' },
  { imgSrc: '32.jpg' },
  { imgSrc: '33.jpg' },
  { imgSrc: '34.jpg' },
  { imgSrc: '35.jpg' },
  { imgSrc: '36.jpg' },
  { imgSrc: '37.jpg' },
  { imgSrc: '38.jpg' },
  { imgSrc: '39.jpg' },
  { imgSrc: '40.jpg' },
  { imgSrc: '41.jpg' },
  { imgSrc: '42.jpg' },
  { imgSrc: '43.jpg' },
  { imgSrc: '44.jpg' },
  { imgSrc: '45.jpg' },
  { imgSrc: '46.jpg' },
  { imgSrc: '47.jpg' },
  { imgSrc: '48.jpg' },
  { imgSrc: '49.jpg' },
  { imgSrc: '50.jpg' },
  { imgSrc: '51.jpg' },
  { imgSrc: '52.jpg' },
  { imgSrc: '53.jpg' },
  { imgSrc: '54.jpg' }
]







